# Generated by Django 4.2.9 on 2025-12-25 02:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_alta', models.DateField(default=datetime.date.today, verbose_name='Fecha de alta')),
                ('prefijo', models.CharField(max_length=10, verbose_name='Prefijo')),
                ('consecutivo', models.PositiveIntegerField(verbose_name='Consecutivo')),
                ('contenedor', models.CharField(max_length=20, verbose_name='Contenedor')),
                ('comentarios', models.CharField(blank=True, help_text='Generado automáticamente: CONCEPTO PREFIJO CONSECUTIVO CONTENEDOR', max_length=100, verbose_name='Comentarios (Referencia)')),
                ('bl_master', models.CharField(blank=True, max_length=50, verbose_name='BL Master')),
                ('pedimento', models.CharField(blank=True, max_length=30, verbose_name='Pedimento')),
                ('factura', models.CharField(blank=True, max_length=30, verbose_name='Factura')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Importe')),
                ('divisa', models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Americanos')], default='MXN', max_length=3, verbose_name='Divisa')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('cerrado', 'Cerrado')], default='pendiente', max_length=20, verbose_name='Estatus')),
                ('fecha_pago', models.DateField(blank=True, null=True, verbose_name='Fecha de pago')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='Fecha ETA')),
                ('dias_libres', models.PositiveIntegerField(default=7, verbose_name='Días libres')),
                ('contador_ediciones', models.PositiveIntegerField(default=0, help_text='Máximo 2 ediciones permitidas para rol Revalidaciones', verbose_name='Contador de ediciones')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('concepto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.concepto', verbose_name='Concepto')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.empresa', verbose_name='Empresa')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.proveedor', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-fecha_alta', '-id'],
                'unique_together': {('prefijo', 'consecutivo')},
            },
        ),
    ]
