# Generated by Django 4.2.9 on 2025-12-29 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ejecutivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='catalogos.proveedor'),
        ),
        migrations.AddField(
            model_name='saldotesoreria',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_saldo', to='catalogos.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='saldotesoreria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_saldo', to='catalogos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='saldotesoreria',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_saldo', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='catalogos.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='contenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prestamos', to='operaciones.contenedor', verbose_name='Contenedor relacionado'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='pedimento',
            name='agente_aduanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedimentos', to='catalogos.agenteaduanal', verbose_name='Agente aduanal'),
        ),
        migrations.AddField(
            model_name='pedimento',
            name='comercializadora',
            field=models.ForeignKey(blank=True, help_text='Puede ser comercializadora ajena', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedimentos', to='catalogos.comercializadora', verbose_name='Comercializadora'),
        ),
        migrations.AddField(
            model_name='pedimento',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedimentos', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='operacionrevalidacion',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_revalidacion', to='catalogos.concepto', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='operacionrevalidacion',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_revalidacion', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='operacionrevalidacion',
            name='ejecutivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_revalidacion', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo'),
        ),
        migrations.AddField(
            model_name='operacionrevalidacion',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_revalidacion', to='catalogos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='operacionrevalidacion',
            name='naviera_cuenta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones', to='catalogos.navieracuenta', verbose_name='Cuenta de naviera'),
        ),
        migrations.AddField(
            model_name='operacionlogistica',
            name='concepto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_logistica', to='catalogos.concepto', verbose_name='Concepto'),
        ),
        migrations.AddField(
            model_name='operacionlogistica',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_logistica', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='operacionlogistica',
            name='ejecutivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_logistica', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo'),
        ),
        migrations.AddField(
            model_name='operacionlogistica',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_logistica', to='catalogos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='operacionlogistica',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operaciones_logistica', to='catalogos.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantias', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='eir_documento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garantias', to='operaciones.documento', verbose_name='Documento EIR'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='naviera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='garantias', to='catalogos.naviera', verbose_name='Naviera'),
        ),
        migrations.AddField(
            model_name='garantia',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='garantias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='clasificacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='operaciones.clasificacion', verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='documento',
            name='contenedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='documento',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
        ),
        migrations.AddField(
            model_name='demora',
            name='contenedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demoras', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='demora',
            name='naviera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demoras', to='catalogos.naviera', verbose_name='Naviera'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenedores', to='catalogos.cliente', verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenedores_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ejecutivo_logistica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenedores_logistica', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo de logística'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ejecutivo_revalidacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenedores_revalidacion', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo de revalidación'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenedores', to='catalogos.empresa', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='naviera',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenedores', to='catalogos.naviera', verbose_name='Naviera'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='puerto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contenedores', to='catalogos.puerto', verbose_name='Puerto'),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contenedores', to='catalogos.terminal', verbose_name='Terminal'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='agente_aduanal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='catalogos.agenteaduanal', verbose_name='Agente aduanal'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='comercializadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones', to='catalogos.comercializadora', verbose_name='Comercializadora'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='contenedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='ejecutivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to=settings.AUTH_USER_MODEL, verbose_name='Ejecutivo de clasificación'),
        ),
        migrations.AddField(
            model_name='clasificacion',
            name='visto_bueno_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vistos_buenos', to=settings.AUTH_USER_MODEL, verbose_name='Visto bueno por'),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('prefijo', 'consecutivo')},
        ),
        migrations.AlterUniqueTogether(
            name='operacionlogistica',
            unique_together={('prefijo', 'consecutivo')},
        ),
    ]
