# Generated by Django 4.2.9 on 2025-12-31 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('operaciones', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='puerto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='catalogos.puerto', verbose_name='Puerto'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_operacion',
            field=models.CharField(choices=[('revalidaciones', 'Revalidaciones'), ('logistica', 'Logística'), ('clasificacion', 'Clasificación')], default='revalidaciones', help_text='Determina en qué sábana aparece el ticket', max_length=20, verbose_name='Tipo de operación'),
        ),
    ]
