# Generated by Django 4.2.9 on 2026-01-03 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0003_ticket_puerto_ticket_tipo_operacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='operacionlogistica',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together=set(),
        ),
    ]
