# Generated by Django 4.2.9 on 2026-01-06 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('operaciones', '0004_alter_operacionlogistica_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='concepto',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='tickets',
                to='catalogos.concepto',
                verbose_name='Concepto'
            ),
        ),
    ]
