# Generated by Django 4.2.9 on 2026-01-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_make_ticket_concepto_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='comprobante_pago',
            field=models.FileField(
                blank=True,
                help_text='PDF o imagen del comprobante de pago',
                null=True,
                upload_to='comprobantes/tickets/%Y/%m/',
                verbose_name='Comprobante de pago'
            ),
        ),
    ]
