# Generated by Django 4.2.9 on 2025-12-27 20:18

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoRevalidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('normal', 'Pago normal'), ('demora', 'Pago de demora'), ('garantia', 'Pago de garantía')], default='normal', max_length=20, verbose_name='Tipo de pago')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('referencia_bancaria', models.CharField(blank=True, max_length=100, verbose_name='Referencia bancaria')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/revalidacion/%Y/%m/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('observaciones_tesoreria', models.TextField(blank=True, verbose_name='Observaciones tesorería')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='operaciones.operacionrevalidacion', verbose_name='Operación de revalidación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_revalidacion', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de revalidación',
                'verbose_name_plural': 'Pagos de revalidación',
                'db_table': 'pagos_revalidacion',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='PagoLogistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('referencia_bancaria', models.CharField(blank=True, max_length=100, verbose_name='Referencia bancaria')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/logistica/%Y/%m/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='operaciones.operacionlogistica', verbose_name='Operación de logística')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_logistica', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago de logística',
                'verbose_name_plural': 'Pagos de logística',
                'db_table': 'pagos_logistica',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CierreOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto final')),
                ('desglose', models.JSONField(blank=True, default=dict, help_text='JSON con el desglose de costos para el comprobante', verbose_name='Desglose de costos')),
                ('garantias_verificadas', models.BooleanField(default=False, help_text='Se verificó el regreso de garantías/EIR', verbose_name='Garantías verificadas')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cierre')),
                ('contenedor', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='operaciones.contenedor', verbose_name='Contenedor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre de operación',
                'verbose_name_plural': 'Cierres de operación',
                'db_table': 'cierres_operacion',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='CierreLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto final')),
                ('desglose', models.JSONField(blank=True, default=dict, verbose_name='Desglose de costos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cierre')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='operaciones.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_legacy', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre (Legacy)',
                'verbose_name_plural': 'Cierres (Legacy)',
                'db_table': 'cierres_legacy',
                'ordering': ['-fecha_cierre'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='ID de operación')),
                ('tipo_operacion', models.CharField(choices=[('logistica', 'Logística'), ('revalidacion', 'Revalidación'), ('legacy', 'Ticket (Legacy)')], default='logistica', max_length=20, verbose_name='Tipo de operación')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('dias_retraso', models.IntegerField(default=0, help_text='Días de retraso respecto al ETA (calculado automáticamente)', verbose_name='Días de retraso')),
                ('concepto_pago', models.CharField(blank=True, max_length=200, verbose_name='Concepto del pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia bancaria')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de operación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago', '-fecha_registro'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='pagos_content_5e7299_idx'), models.Index(fields=['tipo_operacion'], name='pagos_tipo_op_9ada20_idx')],
            },
        ),
    ]
