# Generated by Django 4.2.9 on 2025-12-25 02:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto pagado')),
                ('fecha_pago', models.DateField(default=datetime.date.today, verbose_name='Fecha de pago')),
                ('dias_retraso', models.IntegerField(default=0, help_text='Días de retraso respecto al ETA (calculado automáticamente)', verbose_name='Días de retraso')),
                ('concepto_pago', models.CharField(blank=True, max_length=200, verbose_name='Concepto del pago')),
                ('referencia', models.CharField(blank=True, max_length=100, verbose_name='Referencia bancaria')),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/', verbose_name='Comprobante')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='operaciones.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['-fecha_pago', '-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='CierreOperacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_final', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto final')),
                ('desglose', models.JSONField(blank=True, default=dict, help_text='JSON con el desglose de costos para el comprobante', verbose_name='Desglose de costos')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de cierre')),
                ('ticket', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='operaciones.ticket', verbose_name='Ticket')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por')),
            ],
            options={
                'verbose_name': 'Cierre de operación',
                'verbose_name_plural': 'Cierres de operación',
                'db_table': 'cierres_operacion',
                'ordering': ['-fecha_cierre'],
            },
        ),
    ]
