# Generated by Django 4.2.9 on 2025-12-29 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('operaciones', '0002_initial'),
        ('pagos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pagorevalidacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_revalidacion', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='pagologistica',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='operaciones.operacionlogistica', verbose_name='Operación de logística'),
        ),
        migrations.AddField(
            model_name='pagologistica',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_logistica', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='pago',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Tipo de operación'),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='cierreoperacion',
            name='contenedor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='operaciones.contenedor', verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='cierreoperacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_realizados', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddField(
            model_name='cierrelegacy',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='cierre', to='operaciones.ticket', verbose_name='Ticket'),
        ),
        migrations.AddField(
            model_name='cierrelegacy',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierres_legacy', to=settings.AUTH_USER_MODEL, verbose_name='Cerrado por'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['content_type', 'object_id'], name='pagos_content_5e7299_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['tipo_operacion'], name='pagos_tipo_op_9ada20_idx'),
        ),
    ]
