# Generated by Django 4.2.9 on 2025-12-29 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteAduanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('patente', models.CharField(blank=True, max_length=20, verbose_name='Número de patente')),
                ('banco', models.CharField(blank=True, max_length=50, verbose_name='Banco')),
                ('cuenta', models.CharField(blank=True, max_length=30, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=25, verbose_name='CLABE interbancaria')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Agente aduanal',
                'verbose_name_plural': 'Agentes aduanales',
                'db_table': 'cat_agentes_aduanales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comercializadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Comercializadora',
                'verbose_name_plural': 'Comercializadoras',
                'db_table': 'cat_comercializadoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, max_length=200, verbose_name='Razón social')),
                ('rfc', models.CharField(blank=True, max_length=13, verbose_name='RFC')),
                ('es_principal', models.BooleanField(default=False, help_text='Indica si es MICRA o B&MM (empresas principales del sistema)', verbose_name='Es empresa principal')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'cat_empresas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Naviera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=20, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Naviera',
                'verbose_name_plural': 'Navieras',
                'db_table': 'cat_navieras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True, verbose_name='Nombre')),
                ('banco', models.CharField(blank=True, max_length=50, verbose_name='Banco')),
                ('cuenta', models.CharField(blank=True, max_length=30, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=25, verbose_name='CLABE interbancaria')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'db_table': 'cat_proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Puerto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Puerto',
                'verbose_name_plural': 'Puertos',
                'db_table': 'cat_puertos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('banco', models.CharField(blank=True, max_length=50, verbose_name='Banco')),
                ('cuenta', models.CharField(blank=True, max_length=30, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=25, verbose_name='CLABE interbancaria')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('puerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='terminales', to='catalogos.puerto')),
            ],
            options={
                'verbose_name': 'Terminal',
                'verbose_name_plural': 'Terminales',
                'db_table': 'cat_terminales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo_rol', models.CharField(choices=[('logistica', 'Logística/Operaciones'), ('revalidacion', 'Revalidaciones'), ('ambos', 'Ambos roles')], default='ambos', help_text='Define qué rol puede usar este concepto', max_length=20, verbose_name='Tipo de rol')),
                ('es_base', models.BooleanField(default=True, help_text='Los conceptos base aplican para todos', verbose_name='Es concepto base')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('naviera', models.ForeignKey(blank=True, help_text='Si es específico de una naviera', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='catalogos.naviera')),
                ('puerto', models.ForeignKey(blank=True, help_text='Si es específico de un puerto', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='catalogos.puerto')),
                ('terminal', models.ForeignKey(blank=True, help_text='Si es específico de una terminal', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='catalogos.terminal')),
            ],
            options={
                'verbose_name': 'Concepto',
                'verbose_name_plural': 'Conceptos',
                'db_table': 'cat_conceptos',
                'ordering': ['tipo_rol', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('prefijo', models.CharField(max_length=10, unique=True, verbose_name='Prefijo')),
                ('contacto', models.CharField(blank=True, max_length=100, verbose_name='Contacto')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('empresa_asociada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes', to='catalogos.empresa', verbose_name='Empresa asociada')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cat_clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Aduana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('codigo', models.CharField(blank=True, max_length=10, verbose_name='Código')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('puerto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aduanas', to='catalogos.puerto')),
            ],
            options={
                'verbose_name': 'Aduana',
                'verbose_name_plural': 'Aduanas',
                'db_table': 'cat_aduanas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NavieraCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_concepto', models.CharField(help_text='Ej: Demoras, Limpieza/Revalidación, Garantía USD, etc.', max_length=100, verbose_name='Tipo de concepto')),
                ('beneficiario', models.CharField(max_length=200, verbose_name='Beneficiario')),
                ('banco', models.CharField(max_length=100, verbose_name='Banco')),
                ('cuenta', models.CharField(blank=True, max_length=50, verbose_name='Número de cuenta')),
                ('clabe', models.CharField(blank=True, max_length=25, verbose_name='CLABE interbancaria')),
                ('aba_swift', models.CharField(blank=True, max_length=50, verbose_name='ABA / SWIFT')),
                ('moneda', models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Americanos')], default='USD', max_length=3, verbose_name='Moneda')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('naviera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='catalogos.naviera', verbose_name='Naviera')),
            ],
            options={
                'verbose_name': 'Cuenta de naviera',
                'verbose_name_plural': 'Cuentas de navieras',
                'db_table': 'cat_naviera_cuentas',
                'ordering': ['naviera', 'tipo_concepto'],
                'unique_together': {('naviera', 'tipo_concepto', 'moneda')},
            },
        ),
    ]
