# Generated by Django 4.2.9 on 2025-12-29 03:53

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(blank=True, help_text='Se auto-llena del cliente pero puede modificarse', max_length=200, verbose_name='Razón social')),
                ('consecutivo', models.PositiveIntegerField(help_text='Número consecutivo de la cotización', verbose_name='Consecutivo')),
                ('fecha_emision', models.DateField(verbose_name='Fecha de emisión')),
                ('bl_master', models.CharField(max_length=50, verbose_name='BL Master')),
                ('contenedor', models.CharField(max_length=20, verbose_name='Contenedor')),
                ('terminal', models.CharField(blank=True, max_length=100, verbose_name='Terminal')),
                ('naviera', models.CharField(blank=True, max_length=100, verbose_name='Naviera')),
                ('pedimento', models.CharField(blank=True, help_text='Número de pedimento aduanal', max_length=30, verbose_name='# Pedimento')),
                ('eta', models.DateField(blank=True, null=True, verbose_name='ETA')),
                ('fecha_entrega', models.DateField(blank=True, null=True, verbose_name='Fecha de entrega')),
                ('dias_demoras', models.PositiveIntegerField(default=0, verbose_name='Días de demoras')),
                ('dias_almacenaje', models.PositiveIntegerField(default=0, verbose_name='Días de almacenaje')),
                ('divisa', models.CharField(choices=[('MXN', 'Pesos Mexicanos'), ('USD', 'Dólares Americanos')], default='MXN', max_length=3, verbose_name='Divisa')),
                ('costo_demoras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='延误 / Demoras')),
                ('costo_almacenaje', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='贮存 / Almacenaje')),
                ('costo_gastos_portuarios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='港口费用 / Gastos Portuarios')),
                ('costo_operativos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='营运成本 / Costos Operativos')),
                ('costo_apoyo', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Este concepto se destaca en rojo en el PDF', max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='支援 / Apoyo')),
                ('costo_impuestos', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='税收 / Impuestos')),
                ('costo_liberacion', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='摆脱遗弃 / Liberación de Abandono')),
                ('costo_transporte', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='運輸 / Transporte')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='全部的 / Total')),
                ('tipo_cambio', models.DecimalField(blank=True, decimal_places=4, help_text='Tipo de cambio USD/MXN', max_digits=8, null=True, verbose_name='Tipo de cambio')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('aduana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='catalogos.aduana', verbose_name='Aduana')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='catalogos.cliente', verbose_name='Cliente')),
                ('puerto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='catalogos.puerto', verbose_name='Puerto')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'db_table': 'cotizaciones',
                'ordering': ['-fecha_emision', '-id'],
            },
        ),
    ]
