# Generated by Django 4.2.9 on 2025-12-29 03:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cotizaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterUniqueTogether(
            name='cotizacion',
            unique_together={('cliente', 'consecutivo')},
        ),
    ]
