# Generated by Django 4.2.9 on 2025-12-29 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('CREAR_TICKET', 'Crear ticket'), ('EDITAR_TICKET', 'Editar ticket'), ('EDITAR_ETA', 'Editar fecha ETA'), ('EDITAR_DIAS_LIBRES', 'Editar días libres'), ('REGISTRAR_PAGO', 'Registrar pago'), ('CERRAR_OPERACION', 'Cerrar operación'), ('CREAR_COTIZACION', 'Crear cotización'), ('CREAR_USUARIO', 'Crear usuario'), ('CAMBIAR_PASSWORD', 'Cambiar contraseña'), ('TOGGLE_USUARIO', 'Activar/Desactivar usuario'), ('CREAR_CATALOGO', 'Crear catálogo'), ('EDITAR_CATALOGO', 'Editar catálogo'), ('ELIMINAR_CATALOGO', 'Eliminar catálogo')], max_length=30, verbose_name='Tipo de acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('modelo', models.CharField(blank=True, max_length=50, verbose_name='Modelo afectado')),
                ('objeto_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID del objeto')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos nuevos')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
            ],
            options={
                'verbose_name': 'Registro de bitácora',
                'verbose_name_plural': 'Bitácora de auditoría',
                'db_table': 'bitacora',
                'ordering': ['-fecha'],
            },
        ),
    ]
